---
# Install system apt packages
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: install packages
    yum:
      name: "python3-pip"
      state: "present"
    yum:
      name: "git"
      state: "present"

# Install the app, note: don't do these tasks with become sudo
- hosts: webservers
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/DylanJerault/projet_poei_grp3.git'
      dest: /home/ec2-user/app
      update: yes  # Does a git pull if the repo already exists
  - name: install venv
    pip:
      name: "virtualenv"
      executable: pip-3.3
      version: "15.0.3"
      state: "present"   
  - name: install modules in a virtualenv
    pip:
      requirements: /home/ec2-user/app/requirements.txt
      executable: pip-3.3
      virtualenv: /home/ec2-user/app/env
      virtualenv_python: python3.7

# Run a quick test to verify the site is working
- hosts: webservers
  tasks:
  - name: get url
    get_url:
      url: http://54.183.180.72:5000
      dest: /
