---
# Install system apt packages
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:        
  - name: execute pip's installation
    shell:
      cmd: yum install python3-pip
         
  - name: install packages
    yum:
      name: "git"
      state: "present"

  - name: Creates directory
    file:
      path: /home/ec2-user/app
      state: directory
      
  - name: Add pip folder to path
    shell:
      chdir: app
      cmd: export PATH=$PATH:/home/ec2-user/app

# Install the app, note: don't do these tasks with become sudo
- hosts: webservers
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/DylanJerault/projet_poei_grp3.git'
      dest: /home/ec2-user/app
      update: yes  # Does a git pull if the repo already exists
  - name: install venv
    ansible.builtin.shell:
      cmd: pip3 install virtualenv
    
  - name: install flask pytest
    ansible.builtin.shell:
      cmd: pip3 install flask pytest
      
#  - name: install modules in a virtualenv
#    ansible.builtin.shell:
#      cmd: python3 -m venv venv
      
#  - name: lancement venv
#    ansible.builtin.shell:
#      cmd: source venv/bin/activate    
      
  - name: lancement app
    ansible.builtin.shell:
      cmd: python3 app.py 
      
