---
# Install system apt packages
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
  - name: DL get-pip files
    shell:
      cmd: curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
         
  - name: execute pip's installation
    shell:
      cmd: python3 get-pip.py
         
  - name: install packages
    yum:
      name: "git"
      state: "present"

  - name: Creates directory
    file:
      path: /home/ec2-user/app
      state: directory
      
  - name: Add pip folder to path
    shell:
      chdir: app
      cmd: export PATH=$PATH:/home/ec2-user/app

# Install the app, note: don't do these tasks with become sudo
- hosts: webservers
  tasks:
  - name: clone repo
    git:
      repo: 'https://github.com/DylanJerault/projet_poei_grp3.git'
      dest: /home/ec2-user/app
      update: yes  # Does a git pull if the repo already exists
  - name: install venv
    ansible.builtin.shell:
      cmd: pip3 install virtualenv
    
  - name: install modules in a virtualenv
    pip:
      requirements: /home/ec2-user/app/requirements.txt
      virtualenv: /home/ec2-user/app/env
      virtualenv_python: python3.7

# Run a quick test to verify the site is working
- hosts: webservers
  tasks:
  - name: get url
    get_url:
      url: http://3.101.33.193:5000
      dest: /
